### ISSUE TITLE
Unable to open sgf after last update

### ISSUE THREAD

**Issue by Kerra** [SabakiHQ/Sabaki#363]
I am unable to load sgf files directly (from file) or manually (in Sabaki). The board stays in the exact same state as it was before. I didn't encounter this behaviour in the previous version.

**Comment by yishn** [comment]
Which operating system do you use?

**Comment by Kerra** [comment]
Windows 10 (fresh install). 
Reconfirmed, that v0.33.3 has no issues.

**Comment by yishn** [comment]
Hm... I can open files just fine on Windows 10 using the downloaded executable. Can you open [developer tools](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/debugging.md) and see if there's any error messages when you open a file?

**Comment by Kerra** [comment]
![capture](https://user-images.githubusercontent.com/33136533/38331902-e0d715c0-3854-11e8-8dba-5b66e195bd64.PNG)
Here we go. Maybe it is useful to mention that I use the 64-bit version.

**Comment by yishn** [comment]
It seems like node.js has issues opening the file. Are you able to [build Sabaki yourself](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/building-tests.md)? If so, can you confirm this issue still exists in your own build?

You mentioned that the file can be opened with v0.33.3? Is it a specific file or are you not able to open any files whatsoever? If it's a specific file, can you post it here?

**Comment by Kerra** [comment]
I have tried opening at least 10 different files (most of the past), none worked in v0.33.4. 
I'll try building it myself now.

**Comment by yishn** [comment]
Are you using OneDrive? A cursory search has led me to [this Electron issue](https://github.com/electron/electron/issues/11570), but it should be fixed already in v1.8.4 which Sabaki v0.33.4 is using. May it's a regression...

**Comment by Kerra** [comment]
I am using OneDrive, yes. But I never had any problems before using "on-demand". Even if the files are already downloaded it didn't work with v0.33.4.

I just built the project and can confirm that the issue still exists.

**Comment by yishn** [comment]
Even so, just to make sure, can you open SGF files outside of OneDrive? It is a recent Electron issue after all.

**Comment by Kerra** [comment]
Okay, moving it away from OneDrive really fixed it. Very strange though, that it happens with "local present" files. 

Anyway, thank you for your time!
